"""Helpers for referring to user content in logs without reproducing it."""

from __future__ import annotations

import hashlib
import logging
import re

__all__ = ["install_control_character_escaping", "question_ref"]


def question_ref(question: str | None) -> str:
    """A stable, non-reversible handle for a user's question.

    Logs used to carry the question itself, at INFO, on ordinary retrieval paths
    -- so anyone with log access read what every user asked, and truncating to
    the first 50 characters still reproduced the substance. The digest keeps the
    one property the logs actually needed: the same question produces the same
    handle, so a request can still be followed across lines and across services.

    Length is kept because it is useful for spotting empty or runaway inputs and
    reveals nothing on its own.
    """

    text = str(question or "")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
    return f"q[{digest} len={len(text)}]"


# C0 and C1 control characters, minus tab: a tab cannot start a new log line and
# legitimately appears in structured output. Newline and carriage return are the
# ones that matter -- they are what turns one attacker-controlled field into a
# second log record that looks like it came from this application.
_CONTROL_CHARACTERS = re.compile(r"[\x00-\x08\x0a-\x1f\x7f-\x9f]")

_INSTALLED = False


def _escaped(text: str) -> str:
    """Replace control characters with a visible escape, rather than dropping them.

    Dropping would silently rewrite the value; escaping keeps the evidence that
    something tried to inject one, which is the thing an operator reading the log
    afterwards actually wants to see.
    """

    return _CONTROL_CHARACTERS.sub(lambda m: f"\\x{ord(m.group()):02x}", text)


def install_control_character_escaping() -> None:
    """Make it impossible for a logged value to forge a log line.

    `pythonsecurity:S5145` fires wherever caller-controlled data reaches a
    logging call. In this application every such site logs an *identifier* --
    an execution id, a user key, a system name, a cache prefix -- not free text,
    so the risk is not disclosure but forgery: a path parameter carrying `%0A`
    decodes to a newline, and one log record becomes two.

    Fixing that at each call site means finding them all and keeping them found.
    This is the same defect in one place instead: a `LogRecord` factory that
    escapes control characters in the message and its arguments as the record is
    built, so it holds for every logger, every handler, and every call site that
    has not been written yet.

    Deliberately not touched: `exc_info`. A traceback is generated by the
    interpreter rather than by a caller, and mangling one would cost more than
    the forgery it prevents.

    Note for anyone comparing this against a scanner: Sonar's taint analysis does
    not see a record factory, so the S5145 findings stay open regardless. They
    are marked with a pointer here. The point of this function is the property,
    not the finding.
    """

    global _INSTALLED
    if _INSTALLED:
        return

    previous = logging.getLogRecordFactory()

    def factory(*args, **kwargs):
        record = previous(*args, **kwargs)
        if isinstance(record.msg, str):
            record.msg = _escaped(record.msg)
        if record.args:
            if isinstance(record.args, dict):
                record.args = {k: _escaped(v) if isinstance(v, str) else v for k, v in record.args.items()}
            else:
                record.args = tuple(_escaped(a) if isinstance(a, str) else a for a in record.args)
        return record

    logging.setLogRecordFactory(factory)
    _INSTALLED = True
