"""Compatibility exports for the canonical synthesis templates."""

from app.agents.synthesizer.templates import (
    COMPARISON_TEMPLATE,
    CONCEPT_TEMPLATE,
    COT_REASONING_PROMPT,
    GENERAL_TEMPLATE,
    HEDGING_GUIDELINES,
    PROCEDURAL_TEMPLATE,
    QUERY_TYPE_COMPARISON,
    QUERY_TYPE_CONCEPT,
    QUERY_TYPE_GENERAL,
    QUERY_TYPE_PROCEDURAL,
    QUERY_TYPE_RELATIONSHIP,
    RELATIONSHIP_TEMPLATE,
    QueryType,
    get_answer_template,
    get_cot_reasoning_prompt,
    get_hedging_guidelines,
    infer_query_type,
)

__all__ = [
    "QUERY_TYPE_CONCEPT",
    "QUERY_TYPE_COMPARISON",
    "QUERY_TYPE_RELATIONSHIP",
    "QUERY_TYPE_PROCEDURAL",
    "QUERY_TYPE_GENERAL",
    "QueryType",
    "CONCEPT_TEMPLATE",
    "COMPARISON_TEMPLATE",
    "RELATIONSHIP_TEMPLATE",
    "PROCEDURAL_TEMPLATE",
    "GENERAL_TEMPLATE",
    "get_answer_template",
    "infer_query_type",
    "COT_REASONING_PROMPT",
    "get_cot_reasoning_prompt",
    "HEDGING_GUIDELINES",
    "get_hedging_guidelines",
]
