import argparse
import json
import subprocess
import sys
from pathlib import Path


def _run_eval(dataset: str, autotune: bool = False, strategy: str = "") -> dict:
    cmd = [sys.executable, "scripts/eval_retrieval.py", "--dataset", dataset]
    if autotune:
        cmd.append("--autotune")
    if strategy:
        cmd.extend(["--strategy", strategy])
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return {"ok": False, "error": "eval_script_failed", "stderr": proc.stderr.strip()}
    try:
        payload = json.loads(proc.stdout.strip() or "{}")
    except Exception:
        return {"ok": False, "error": "invalid_eval_output", "stdout": proc.stdout.strip()}
    return {"ok": True, "payload": payload}


def main() -> int:
    parser = argparse.ArgumentParser(description="CI quality gate for retrieval and grounding quality.")
    parser.add_argument("--dataset", default="data/eval/retrieval_eval.jsonl")
    parser.add_argument("--min-recall", type=float, default=0.35)
    parser.add_argument("--require-runtime", action="store_true")
    parser.add_argument("--auto-rollback-file", default="")
    parser.add_argument("--strategy", default="")
    parser.add_argument("--report-md", default="")
    args = parser.parse_args()

    def _emit_rollback(reason: str) -> None:
        target = str(args.auto_rollback_file or "").strip()
        if not target:
            return
        p = Path(target)
        p.parent.mkdir(parents=True, exist_ok=True)
        payload = [
            "# auto rollback profile generated by ci_quality_gate",
            f"# reason={reason}",
            "RETRIEVAL_STRATEGY=baseline",
            "QUERY_REWRITE_ENABLED=false",
            "QUERY_DECOMPOSE_ENABLED=false",
            "RANK_FEATURE_ENABLED=false",
            "DYNAMIC_RETRIEVAL_ENABLED=false",
        ]
        p.write_text("\n".join(payload) + "\n", encoding="utf-8")

    def _write_report(title: str, payload: dict) -> None:
        target = str(args.report_md or "").strip()
        if not target:
            return
        p = Path(target)
        p.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# CI Quality Report",
            "",
            f"- title: {title}",
            f"- dataset: {args.dataset}",
            f"- strategy: {str(args.strategy or '').strip().lower() or 'default'}",
            "",
            "```json",
            json.dumps(payload, ensure_ascii=False, indent=2),
            "```",
            "",
        ]
        p.write_text("\n".join(lines), encoding="utf-8")

    result = _run_eval(args.dataset, autotune=False, strategy=str(args.strategy or "").strip().lower())
    if not result.get("ok"):
        _emit_rollback("eval_script_failed")
        _write_report("eval_script_failed", result)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 2
    payload = result.get("payload", {})
    if payload.get("error"):
        if args.require_runtime:
            _emit_rollback("runtime_unavailable")
            out = {"ok": False, "reason": "runtime_unavailable", "payload": payload}
            _write_report("runtime_unavailable", out)
            print(json.dumps(out, ensure_ascii=False, indent=2))
            return 3
        out = {"ok": True, "reason": "runtime_unavailable_but_allowed", "payload": payload}
        _write_report("runtime_unavailable_but_allowed", out)
        print(json.dumps(out, ensure_ascii=False, indent=2))
        return 0

    recall = float(payload.get("recall_at_k", 0.0) or 0.0)
    ok = recall >= args.min_recall
    out = {"ok": ok, "min_recall": args.min_recall, "recall_at_k": recall, "payload": payload}
    _write_report("threshold_check", out)
    print(json.dumps(out, ensure_ascii=False, indent=2))
    if not ok:
        _emit_rollback("recall_below_threshold")
    return 0 if ok else 4


if __name__ == "__main__":
    raise SystemExit(main())
